version: "3"

services:
  db:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
  bot:
    build: .
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/test_db
      - TOKEN=
      - PREFIX=!
      - JWT_KEY=
    volumes:
      - .:/app
    depends_on:
      - db
